### ISSUE TITLE
GuzzleHttp v6 and v7 conflict with composer

### ISSUE THREAD

**Issue by ze6t9er** [mailslurp/mailslurp-client-php#1]
Hi,

I've just created a Mailslurp account to test the API and see if it fits our needs before upgrading my account.

I already have other packages installed via composer and using guzzlehttp v7.3.

However, when trying to execute the composer require mailslurp/mailslurp-client-php command, the requirements are GuzzleHttp 6.X, which is not compatible with the version we currently use with other packages (locked at 7.3.0).

Do you plan to upgrade your dependency requirement on Guzzle to v7.X soon or is there another trick so we can use mailslurp php api without having to rewrite some code ?

![Capture d’écran 2021-04-20 à 13 36 05](https://user-images.githubusercontent.com/75019024/115389468-6b00f000-a1dd-11eb-81f8-c8345b94c502.png)

**Comment by jrbautista** [comment]
Any luck with this? I'm having this issue too. Would be glad if at least they reply to this issue.

![Screenshot_1](https://user-images.githubusercontent.com/93120616/171335587-325fd752-05dc-428e-8fe3-94166f9958d9.png)

**Comment by jackmahoney** [comment]
Hi both, sorry we have now updated the library to use more up to date guzzle. Can you try with the latest package?

**Comment by alexkb** [comment]
@jackmahoney on the master branch the composer.json currently still shows `"guzzlehttp/guzzle": "^6.2"` here: https://github.com/mailslurp/mailslurp-client-php/blob/master/composer.json#L27
![image](https://user-images.githubusercontent.com/473434/205789152-96bf6955-2065-4fd0-9571-fbd33b1cea79.png)

**Comment by jackmahoney** [comment]
Hi sorry for the delay everyone, we have made this a higher priority.

**Comment by jackmahoney** [comment]
Hi @alexkb, @jrbautista @ze6t9er we have upgraded the build tools to the latest version and bumped guzzle to v7. There is a new release here https://github.com/mailslurp/mailslurp-client-php/releases/tag/15.15.5

**Comment by jackmahoney** [comment]
Packagist link here: https://packagist.org/packages/mailslurp/mailslurp-client-php#15.15.5

Thanks for your patience
